config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks/:id", to: "tasks#show", as: :task
  get "task/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update", as: :update_task
  delete "tasks/:id", to: "tasks#destroy", as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params) # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container mt-3" style="width:600px;">
  <h1>Edit task</h1>
  <%= form_with model: @task do |f| %>
    <%= f.label :title, class: "form-label"%>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.label :details, class: "form-label" %>
    <%= f.text_field :details, class: "form-control" %>
    <%= f.submit class: "btn btn-primary" %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% end %>
  <p><%= link_to "Back to list", tasks_path %></p>
</div>

app/views/tasks/index.html.erb
<div class="container mt-3" style="width:600px;">
  <h1>My tasks</h1>
   <ul>
    <% @tasks.each do |task| %>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
        <%= link_to task.title, task_path(task)%>
        <%= link_to destroy_task_path(task),
          data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}"} do%>
          <i class="fa-solid fa-trash-can"></i>
        <% end %>
      </label>
      </div>
    <% end %>
  </ul>
  <%= link_to "Add a new task", new_task_path, class: "btn btn-primary" %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-3" style="width:600px;">
  <h1>New task</h1>
  <%= form_with model: @task do |f| %>
    <div class="mb-3">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :details, class: "form-label"%>
      <%= f.text_field :details, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-primary"  %>
  <% end %>
  <p><i class="fa-solid fa-arrow-left"></i><%= link_to "Back to list", tasks_path, class: "btn btn-secondary mt-3" %></p>
</div>

app/views/tasks/show.html.erb
<div class="container mt-3" style="width:600px;">
  <h2><%= @task.title %></h2>
  <p><i class="fa-solid fa-arrow-left"></i><%= link_to "Back to list", tasks_path %></p>
  <p><%= @task.details %></p>
  <% if @task.completed %>
  <p> This task is completed ! </p>
  <% else %>
  <p> This task is not completed yet</p>
  <% end %>
  <p><%= link_to "Edit this task", edit_task_path %></p>
</div>